baseURL = "https://seaindream.me/"
languageCode = "zh-cn"
title = "SeainDream"
theme = "PaperMod"

[params]
  [params.profileMode]
    enabled = false

[menu]
  [[menu.main]]
    name = "摄影"
    url = "/photography/"
    weight = 1
  [[menu.main]]
    name = "音乐"
    url = "/music/"
    weight = 2
  [[menu.main]]
    name = "随笔"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "留言"
    url = "/guestbook/"
    weight = 4
  [[menu.main]]
    name = "笔记"
    url = "/notes/"
    weight = 5